name: miscelaneos_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0-42.1.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  flutter_riverpod: ^2.3.9
  geolocator: ^10.1.0
  go_router: ^12.1.3
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.1.0
  sensors_plus: ^4.0.1
  workmanager: ^0.5.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
